# Numpy 

In [48]:
import numpy as np

#### Create an array of 10 zeroes

In [49]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [50]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [51]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an Array of integers 10 - 50

In [52]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an Array of all the even integers 10 - 50

In [53]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 Matrix ranging from 0 - 8

In [54]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 Identity matrix

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use numpy to generate a random number between 0 and 1

In [56]:
arr = np.random.rand(1)
arr

array([0.96042307])

#### Use numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [57]:
np.random.randn(25)

array([ 2.1518596 ,  1.39374147,  1.92778508, -0.97476015,  0.83819939,
       -0.5633357 ,  0.60394657,  0.41620711, -0.60242784,  1.28809026,
        0.3373137 , -0.27377409, -0.30595684,  0.47370674, -0.45895434,
        0.77628665, -0.43332051, -1.03647539, -0.04687929,  0.69816816,
        1.50425213,  0.37864003, -1.11638827, -0.15893876,  1.30293016])

#### Create the following matrix

In [58]:
np.arange(1,101)/100
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### Create an array of 20 linearly spaced points between 0 and 1

In [59]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [60]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
arr[2:,1:]
# mat = (arr[0:4], arr[5:9], arr[10:15])
# mat

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [62]:
arr[1:,2:] #[row-start:row-end,col]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [63]:
arr = np.arange(1,26).reshape(5,5)
arr[3:4,4]

array([20])

In [64]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [65]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
a[2:,2:3]
a[2:3,2]

array([11])

In [67]:
arr = np.arange(1,26).reshape(5,5)
arr[4]

array([21, 22, 23, 24, 25])

#### Get the sum of all the numbers in a matrix

In [68]:
arr.sum()

325

#### Get the standard deviation of all the numbers in a matrix

In [69]:
arr.std()

7.211102550927978

#### Get the sum of all the columns in a matrix

In [70]:
array = np.arange(1,26).reshape(5,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [71]:
array.sum(axis=0) #sum of columns

array([55, 60, 65, 70, 75])

In [72]:
array.sum(axis=1) #sum of rows

array([ 15,  40,  65,  90, 115])

---

## Questions

#### 1. Create 1D, 2D and 3D array

In [73]:
#1D
oneD = np.array(1)
oneD

array(1)

In [74]:
#2D
twoD = np.arange(10,20).reshape(2,5)
twoD

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [75]:
#3D
threeD = np.arange(10,37).reshape(3,3,3)
threeD

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

#### 2. Print datatype of an array

In [76]:
twoD.dtype

dtype('int64')

#### 3. Print shape and dimensions of all the three different arrays

In [93]:
print(oneD.ndim)
oneD.shape

0


()

In [92]:
print(twoD.ndim)
twoD.shape

2


(2, 5)

In [91]:
print(threeD.ndim)
threeD.shape

3


(3, 3, 3)

#### 4. Create a 1D array of 12 zeroes

In [80]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 5. Create a 2D array filled with ones

In [81]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 6. Create a 1D array named Maths Marks out of 100 having 20 elements

In [82]:
mathsMarks = np.random.randint(0, 101, 20)
mathsMarks

array([ 15,  82,  15,  22,  72,  84,  17,  43,  48,  32,  47,  48,  16,
        21,  77, 100,  93,   8,  28,  51])

#### 7. Sort the above array in ascending or descending array.

In [94]:
# Ascending order
asc = np.sort(mathsMarks)
asc

array([  8,  15,  15,  16,  17,  21,  22,  28,  32,  43,  47,  48,  48,
        51,  72,  77,  82,  84,  93, 100])

In [98]:
# Descending order
dsc = np.sort(mathsMarks)[::-1]
print(dsc)

# method 2
dsc2 = np.flip(asc)
dsc2

[100  93  84  82  77  72  51  48  48  47  43  32  28  22  21  17  16  15
  15   8]


array([100,  93,  84,  82,  77,  72,  51,  48,  48,  47,  43,  32,  28,
        22,  21,  17,  16,  15,  15,   8])

#### 8. Create a copy of sorted array to another variable by deep copying

In [86]:
marks = mathsMarks.copy()
marks

array([ 15,  82,  15,  22,  72,  84,  17,  43,  48,  32,  47,  48,  16,
        21,  77, 100,  93,   8,  28,  51])

#### 9. Create a 2D array of 5x5 which is an identify matrix and then convert to 1D array.

In [112]:
im = np.eye(5)
print(im)
print("Method 1: ",im.ravel())
print("Method 2: ",im.flatten())
print("Method 3: ",im.reshape(25))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Method 1:  [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 1.]
Method 2:  [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 1.]
Method 3:  [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 1.]


#### 10. Create a 2D array of 3x3. Add one more row to it.

In [115]:
mat1 = np.arange(1,10).reshape(3,3)
mat2 = np.array([11,12,13])
mat = np.vstack((mat1,mat2))
print("Arr1: \n", mat1)
print("Arr2: \n", mat2)
print("Added Row: \n",mat)

Arr1: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Arr2: 
 [11 12 13]
Added Row: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]


#### 11. Split the above array horizontally and vertically

In [123]:
# Horizontal
np.hsplit(mat,3)

[array([[ 1],
        [ 4],
        [ 7],
        [11]]),
 array([[ 2],
        [ 5],
        [ 8],
        [12]]),
 array([[ 3],
        [ 6],
        [ 9],
        [13]])]

In [117]:
# Vertical
np.vsplit(mat,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [11, 12, 13]])]

#### 12. Create a 4x4 identity matrix. Add 4 to each element

In [127]:
iMat = np.eye(4)
iMat += 4
iMat

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

#### 13. Create 1-D array. Initialize with floating point values. Display its ceil, floor and round (with 2 decimal's).

In [230]:
arr2 = np.array([2.45, 5.69, 7.83])
arr = np.random.uniform(1,9,3)
arr

array([4.80241065, 8.91385521, 1.15814568])

In [231]:
np.ceil(arr)

array([5., 9., 2.])

In [232]:
np.floor(arr)

array([4., 8., 1.])

In [233]:
np.round(arr)

array([5., 9., 1.])

#### 14. Create 5x5 matrix. Display min, max, variance and standard deviation column-wise.


In [147]:
matrix = np.random.randint(1, 100, (5, 5))
matrix

array([[29, 23, 79, 80,  8],
       [ 6, 52, 49,  1, 95],
       [11, 30, 58, 18, 18],
       [91, 46, 60, 66, 29],
       [42, 53, 10, 13, 62]])

In [148]:
# Calculate column-wise statistics
col_min = np.amin(matrix, axis=0)
col_max = np.amax(matrix, axis=0)
col_variance = np.var(matrix, axis=0)
col_std = np.std(matrix, axis=0)

print("Minimum:\n", col_min)
print("Maximum:\n", col_max)
print("Variance:\n", col_variance)
print("Standard deviation:\n", col_std)

Minimum:
 [ 6 23 10  1  8]
Maximum:
 [91 53 79 80 95]
Variance:
 [ 926.96  146.96  519.76  982.64 1021.84]
Standard deviation:
 [30.4460178  12.12270597 22.79824555 31.34708918 31.96623218]


#### 15. Create a null vector of size 10 with 6th value filled with 200.


In [221]:
nullVector = np.empty(10)
nullVector[0:] = 'NaN'
nullVector[5] = 200
print(nullVector)

[ nan  nan  nan  nan  nan 200.  nan  nan  nan  nan]


#### 16. Create a 1-D Array/Vector with values ranging from 100 to 150 in sequence.


In [226]:
arr = np.arange(100, 151)
print(arr)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]


#### 17. Reverse the above vector.


In [225]:
print(arr[::-1])

[150 149 148 147 146 145 144 143 142 141 140 139 138 137 136 135 134 133
 132 131 130 129 128 127 126 125 124 123 122 121 120 119 118 117 116 115
 114 113 112 111 110 109 108 107 106 105 104 103 102 101 100]


#### 18. Create a 5x5 matrix with values ranging from 0-24 using some function.


In [242]:
def matrix(start, end, size):
    return np.linspace(start, end, size, dtype=int)
mat = matrix(0, 24, 25).reshape(5, 5)
print(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 19. Find indices of nonzero elements from (1,0,2,0,0,4,0,8]


In [223]:
array = np.array([1, 0, 2, 0, 0, 4, 0, 8])
nonZero = np.where(array != 0) #where()
print(nonZero)

(array([0, 2, 5, 7]),)


In [222]:
nonZeroo = np.nonzero(array)[0] #nonzero()
print(nonZeroo)

[0 2 5 7]


#### 20. Create a 10x10 matrix with 1 on the borders and 0 inside.


In [248]:
matrix = np.ones((10, 10))
matrix[1:-1, 1:-1] = 0  # Set inner elements to 0
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [254]:
matt = np.zeros((10,10))
matt[0,:] = 1
matt[-1,:] = 1
matt[:,0] = 1
matt[:,-1] = 1
print(matt)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 21. Create 8x8 matrix and fill with 1 and 0 in checkerboard pattern.


In [243]:
def checkerboard(shape):
    return np.indices(shape).sum(axis=0) % 2
print(checkerboard((8,8)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [7]:
import numpy as np
a = np.ones((8,8), dtype=int)
a[::2, ::2] = 0
a[1::2, 1::2] = 0
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Create two 3x3 matrix with random integer values. Perform matrix addition, multiplication and subtraction

In [158]:
mat1 = np.random.randint(1,10, (3,3))
mat2 = np.random.randint(1,10, (3,3))
print(mat1)
print(mat2)

[[5 9 7]
 [4 8 8]
 [2 9 5]]
[[3 5 1]
 [7 4 1]
 [9 6 5]]


In [257]:
sum = mat1 + mat2
sum

array([[ 8, 14,  8],
       [11, 12,  9],
       [11, 15, 10]])

In [261]:
product = mat1 @ mat2
# product = np.dot(mat1,mat2)
product

array([[141, 103,  49],
       [140, 100,  52],
       [114,  76,  36]])

In [161]:
diff = mat1 - mat2
diff

array([[ 2,  4,  6],
       [-3,  4,  7],
       [-7,  3,  0]])

In [240]:
np.full((2,5), np.nan)

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])